### ISSUE TITLE
Button click is not working

### ISSUE THREAD

**Issue by karthi72** [vincentbrison/android-easy-swipelistview#3]
I have added a dynamic layout with n number of buttons in horizontal scroll view,after swipe on any side the horizontal scrollable buttons are visible in back layout,on click of the buttons visible it is working fine after scrolling the horizontal scroll view sometimes button click is working and sometimes it is not working.But that will work after again bringing back the front view started swiping action and again swipes to view the back view.

**Comment by vincentbrison** [comment]
Hello,
As written in the README this library is deprecated, and will not receive any new development. Feel free to fork it and do your own modifications.
BR.
